name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies and Build
        run: |
          yarn install
          yarn build

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Nginx Server
        uses: appleboy/scp-action@v0.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: ~/.ssh/id_rsa
          source: dist/ # 빌드된 Vite 정적 파일 경로
          target: /usr/share/nginx/html/ # Nginx 컨테이너와 연결된 볼륨 경로

      - name: Clean Up SSH Key
        if: always()
        run: rm -f ~/.ssh/id_rsa

  notify:
    needs: [deploy-and-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"content": "[FE] 배포가 완료되었습니다."}' \
               $DISCORD_WEBHOOK